sudo: false
language: node_js
node_js:
- '0.10'
- '0.12'
- iojs
notifications:
  email: false
env:
  global:
  - secure: ebONVsqpDt+6O7gHEj0LYG7yZ8vGjA02F5SmnXp4nE/bYLFEMr8Tzas4nsgZDhj1sM4bWOBRRGq75KH9TV9OazkTCu5a04gsLm3aX2M+3HwqAfO2+etrlGFws3c52BTLOPEhknYHkrjVhTgv9k7H22RZ84vNKDySE5I8rExPvJE=
  - secure: I/gjHjV3ZiBwLPDT3xcdCiF3FbJ7KBYjr25oqQ+SGjSV+EJSiCtbl8EI7pYkoDUoqI0Q9C2d+oszKLczDUvA53diLcnIQZyv521dftYJrlQWxqTXLy0ZOEOyWTZfGkaCe7XOusvKx1uOzI+1EXev8ijoVkHqJ7mh9A+iye9QvGs=
