sudo: false
language: node_js
node_js:
- '0.10'
- '0.12'
- iojs
notifications:
  email: false
env:
  global:
  - secure: HErnnms/J5tVA39dGTtunieKT69XkM0nyKEbpZ59JCmv4/9bwjPjoECB/NaLHdUvCmv8OHs4IZLz0qCZxp/2xKtNbyP5MWoHZpBP4VB++6CxXVJgExfvMp4qrKBIV1h1FkGj7fWLZ2PVZu0DZ9OHMBsv0NS/BoW/pzPcUvpKMps=
  - secure: MoM7TbGD4zMCgjrf4oWxuU1JB3ltnRgTPiZ5IM97HdG81sRa1Y+NxycsgD12xo+otqac9zBu5wClHKzJasjmsWUjgLZXFtHG4wBGF98DENxoP/Y45kxlz880YnV9S2uOzJ9+4rk47yM7xcWI6X+x/m5RNzBaroeGihGjF/tar8Q=
