sudo: false
language: node_js
node_js:
- '0.10'
- '0.12'
- iojs
notifications:
  email: false
env:
  global:
  - secure: jxZWoiCN8e8CvcFBK5Fa+q89oLSu0ZJOKHiv+slCcO1HxIMAL2wyxanETJ07JokSpa8D9JdI+vc74WtTBY4fKdEhBCQ9JT83pgtuyKAAsC/SiTd8+5KZ3JWq/wfr4HPnuCu6J/XdDU0D93ZowW1zW2YyRLcb8+FhgKDwfOqD1GA=
  - secure: kTg/BqUJX1m8YX5NzJEsjAkjYNzvLV+t8LANMaLzt3zzWE/M6/UU74WER3W4WruMTMsHpEuyxhXgzd+qibuBSugrCbcvylo4i6+qDzyw9bk8xJl89sp5y0u/W6F5ZOsniafQ0sC1Y1mGxL7tLAwcHeaB6kR2L5j1wVLJx6SNP2M=
