ui: tape
concurrency: 3
browsers:
  - name: chrome
    version: 36..latest
  - name: ie
    version: 8..latest
  - name: firefox
    version: 31..latest
  - name: iphone
    version: 5.1..latest
  - name: ipad
    version: 5.1..latest
  - name: android
    version: 4.0..latest
  - name: opera
    version: 11..latest
  - name: safari
    version: 5..latest
